export {
    contentInteractionApi,
    useDeleteBookmarkMutation,
    useDeleteLikeMutation,
    useGetAllBookmarkQuery,
    useGetAllLikeQuery,
    useGetCountQuery,
    useGetUserBookmarkedThisPostQuery,
    useGetUserLikedThisPostQuery,
    useLazyGetAllBookmarkQuery,
    useLazyGetAllLikeQuery,
    useLazyGetCountQuery,
    useLazyGetUserBookmarkedThisPostQuery,
    useLazyGetUserLikedThisPostQuery,
    usePostBookmarkMutation,
    usePostLikeMutation,
    useGetCountBookedQuery,
    useLazyGetCountBookedQuery,
} from './contentInteractionApi';
