export {
    contentServiceApi,
    useGetFeedQuery,
    useGetOneQuery,
    useLazyGetOneQuery,
    useLazyGetFeedQuery,
    useGetOnePostQuery,
    useLazyGetOnePostQuery,
    useGetCustomFeedQuery,
    useLazyGetCustomFeedQuery,
    useGetBookmarksFeedQuery,
    useGetLikesFeedQuery,
    useLazyGetBookmarksFeedQuery,
    useLazyGetLikesFeedQuery,
} from './contentServiceApi';
